### PR TITLE
Provide `core.exception.onRangeError`

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
See https://github.com/sociomantic-tsunami/dmqnode/pull/5/commits/47a179a052116a19719db399e924ceef050adbdd

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Code attached

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
LGTM. @leandro-lucarella-sociomantic ?

**Comment by leandro-lucarella-sociomantic** [comment]
I still don't get why is this needed.

**Comment by Burgos** [comment]
User's code for the array performs the array bounds checking and calls this callback if the invalid access has been performed: https://github.com/sociomantic-tsunami/dmqnode/blob/47a179a052116a19719db399e924ceef050adbdd/src/dmqnode/storage/engine/overflow/file/DataFile.d#L454

However, D2 doesn't have `onArrayBoundsError`, but `onRangeError`, so it makes user fix this anomaly in their code, while our intention was always to make switches of the runtime libraries as painless as possible:

https://github.com/sociomantic-tsunami/dmqnode/blob/47a179a052116a19719db399e924ceef050adbdd/src/dmqnode/storage/engine/overflow/file/DataFile.d#L359-L365

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
Probably add a release note?

**Comment by mihails-strasuns-sociomantic** [comment]
Which format? We don't have `relmotes` folder in tangort right now :angel:

**Comment by leandro-lucarella-sociomantic** [comment]
I added one in my PR, I don't see a reason not to use neptune with tangort. :)

**Comment by mihails-strasuns-sociomantic** [comment]
Updated

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Pull request merged**
