### PR TITLE
Deprecate `init` into `initializer`

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Matches change in D2 runtime intended to avoid confusion with built-in
`T.init`

### CODE REVIEW

**Review by nemanja-boric-sociomantic — APPROVED** [review]
LGTM, we have a place in swarm which we had to version based on the `D_Version2`. I don't suppose there are lot of the places where this is used.

**Review by leandro-lucarella-sociomantic — APPROVED** [review]
LGTM too, but I'm curious about where this comes from and how didn't we hit it before...

**Comment by nemanja-boric-sociomantic** [comment]
The swarm case:

https://github.com/sociomantic-tsunami/swarm/blob/8d382b5f788523f9633a49227a89d13f33c488a3/src/swarm/neo/node/ConnectionHandler.d#L646-L653

**Comment by nemanja-boric-sociomantic** [comment]
(the problem is that you need to differentiate between `TypeInfo.init` - the property of the `TypeInfo` type itself and the initializer for the given user type represented by the particular `TypeInfo` instance).

**Comment by mihails-strasuns-sociomantic** [comment]
In one of our apps there was about a dozen of places where initializer was used - I fired this PR after having to version them all out to test with more recent compiler :)

**Comment by mihails-strasuns-sociomantic** [comment]
> how didn't we hit it before

It only got deprecated in 2.074 or something like that

**Comment by mihails-strasuns-sociomantic** [comment]
Updated: clean up legacy double object.di situation

**Comment by nemanja-boric-sociomantic** [comment]
Missing release notes.

**Comment by mihails-strasuns-sociomantic** [comment]
Updated to make it a new alias instead of deprecating new field. Looks like there is some relation between dmd1 and tangort about naming expectation so when I changed old fields, tests started to fail with wrong initializers.

This is simpler and will also do fine for our need.

**Review by leandro-lucarella-sociomantic — COMMENTED** [review]
I had the feeling there was a reason for the `object.di`... Are you sure it is OK? Do we want to do this now that tango RT will be abandoned soon?

**Comment by mihails-strasuns-sociomantic** [comment]
> Are you sure it is OK?

Yes (both because it is how it is done in druntime now and because of checking compiler :)).

**Comment by mihails-strasuns-sociomantic** [comment]
>  Do we want to do this now that tango RT will be abandoned soon?

Not sure. It is rather annoying thing to version out for DMD 2.074+ but we can live without it. Change itself is also pretty simple though.

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @leandro-lucarella-sociomantic

**Comment by mihails-strasuns-sociomantic** [comment]
Ping @leandro-lucarella-sociomantic

**Comment by mathias-baumann-sociomantic** [comment]
Can I try as well?
Okay, here we go!

Ping @leandro-lucarella-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
I hope we don't regret it...

**Pull request merged**
