### PR TITLE
Implement non-variadic runtime handlers

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Based on similar change in druntime, required to support https://github.com/dlang/dmd/pull/6669
The change itself is a pre-requisite to -profile=gc feature as it is close to
impossible to wrap function calls that use C style variadics.

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
Ready for review if anyone is willing ;)
@leandro-lucarella-sociomantic @david-eckardt-sociomantic @mathias-lang-sociomantic ?

**Comment by leandro-lucarella-sociomantic** [comment]
To be honest I don't even know what I'm reviewing here, so I can't give any feedback :(

I hope somebody else can, and if not, feel free to merge and let testing decide if you were right or not! :D

**Comment by nemanja-boric-sociomantic** [comment]
Except that `foo` nested function which I don't think it needs to be nested, LGTM. I wouldn't diverge too far from D2 runtime here, so I would restrain from code-style comments (also means that I would keep this `foo` also nested).

**Comment by mihails-strasuns-sociomantic** [comment]
I have tested this and relevant dmd1 PR with ocean, swarm and few proto repos - should be sufficient to prove change is working. Will proceed with the merge.

**Pull request merged**
