### PR TITLE
Add eventfd bindings

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
D2 runtime reference?

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/dlang/druntime/pull/1800

**Comment by nemanja-boric-sociomantic** [comment]
Feel free to block it on that one if you want.

**Comment by nemanja-boric-sociomantic** [comment]
druntime PR has been merged.

**Pull request merged**
