### PR TITLE
Add bindings to sd_nofify* functions

### PR DESCRIPTION
**Pull request by nemanja-boric-sociomantic**
https://github.com/dlang/druntime/pull/1848

### CODE REVIEW

**Comment by mihails-strasuns-sociomantic** [comment]
As discussed in chat, the main question is if such bindings do belong to runtime modules at all (being bindings to specific library/system and not general platform thing)

**Comment by leandro-lucarella-sociomantic** [comment]
I think systemd and the linux kernel are getting very close, so it doesn't look completely crazy to me to be in the runtime. I would see how it goes in druntime. If they want it there, then we put it in here, otherwise I would put it in ocean.

**Comment by leandro-lucarella-sociomantic** [comment]
I actually think this is more something for Ocean, I don't think it belongs to druntime. I would close both PRs and add it to ocean and even maybe adding a thin, more-Dish, wrapper (and eventually integrate it to the App framework).

**Review by leandro-lucarella-sociomantic — CHANGES_REQUESTED** [review]
I think this should go to Ocean.

**Comment by nemanja-boric-sociomantic** [comment]
Fair enough.

**Pull request closed without merging**
